language: go

go:
  - 1.4

install:
  - export PATH=${PATH}:${HOME}/gopath/bin
  - go get -v -t ./...
  - go get -v golang.org/x/lint/golint
  - go get -v golang.org/x/tools/cmd/vet

script:
  - go vet ./...
  - go test -v ./...
  - go test -v -race ./...
  - golint .
