// generated by stringer -type=tt; DO NOT EDIT

package query

import "fmt"

const _tt_name = "ttGenericttEventClausettEventDeclttEventDeclTypettEventDeclAliasttSeqDeclttNegatedDeclttAnyDeclttWhereClausettEqttNettGtttLtttGettLettAttributeSelectorttConjunctionttDisjunctionttPredicatettWithinClausettDuration"

var _tt_index = [...]uint8{9, 22, 33, 48, 64, 73, 86, 95, 108, 112, 116, 120, 124, 128, 132, 151, 164, 177, 188, 202, 212}

func (i tt) String() string {
	if i >= tt(len(_tt_index)) {
		return fmt.Sprintf("tt(%d)", i)
	}
	hi := _tt_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _tt_index[i-1]
	}
	return _tt_name[lo:hi]
}
