// generated by stringer -type=tt; DO NOT EDIT

package query

import "fmt"

const _tt_name = "ttGenericttNumericLiteralttStringLiteralttEventClausettEventDeclttEventDeclTypettEventDeclAliasttSeqDeclttNegatedDeclttAnyDeclttWhereClausettEqttNettGtttLtttGettLettAttributeSelectorttEquivalenceTestttConjunctionttDisjunctionttPredicatettWithinClausettDuration"

var _tt_index = [...]uint16{0, 9, 25, 40, 53, 64, 79, 95, 104, 117, 126, 139, 143, 147, 151, 155, 159, 163, 182, 199, 212, 225, 236, 250, 260}

func (i tt) String() string {
	if i+1 >= tt(len(_tt_index)) {
		return fmt.Sprintf("tt(%d)", i)
	}
	return _tt_name[_tt_index[i]:_tt_index[i+1]]
}
